# Generated by Django 3.2.25 on 2024-04-27 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfil'),
        ('locais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locais',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
