# Generated by Django 5.0.6 on 2024-05-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0002_alter_locais_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locais',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
