# Generated by Django 5.0.6 on 2024-06-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locais', '0004_alter_locais_maquina'),
        ('maquinas', '0002_alter_maquinas_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locais',
            name='maquina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maquinas.maquinas'),
        ),
    ]
