# Generated by Django 5.0.6 on 2024-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='status',
            field=models.CharField(choices=[('A', 'ativo'), ('B', 'Desativado')], max_length=1),
        ),
    ]
